# The minimum amount of voxels that should separate any two objects
object_min_distance: 2

# Config for the octopus shape
Octopus:
  # Will choose a random integer between [min,max-1]
  # This will be the number of tentacles generated on a particular octopus
  min_num_tentacles: 3
  max_num_tentacles: 7
  # Length of each tentacle is chosen as some random number between [min,max]
  # Unit is voxels, ie the number of voxels add to the spine of the walk
  min_tentacle_length: 35
  max_tentacle_length: 55
  # If True, each walk will have branches connected to it if it is long enough
  branching: True
  length_between_branches: 5
  shape: "Spheroid"
  min_width: 2
  max_width: 2
