# The minimum amount of voxels that should separate any two objects
object_min_distance: 4

Spheroid:
  center_placement_border: 5
  min_radius: 2
  max_radius: 2

Torus:
  center_placement_border: 4
  min_major_radius: 4
  max_major_radius: 4
  min_minor_radius: 2
  min_holes: 5
  max_holes: 5
