# The minimum amount of voxels that should separate any two objects
object_min_distance: 5

Spheroid:
  center_placement_border: 5
  min_radius: 5
  max_radius: 5

Torus:
  center_placement_border: 4
  min_major_radius: 3
  max_major_radius: 3
  min_minor_radius: 1
  min_holes: 5
  max_holes: 5
