# The minimum amount of voxels that should separate any two objects
object_min_distance: 4

# Config for the spheroid
# center_placement_border: places the object at least 4 voxels away from the border. This can help the algorithm find a valid spot faster.
# min_radius: minimum radius of the spheroid
# max_radius: maximum radius of the spheroid
Spheroid:
  center_placement_border: 4
  min_radius: 4
  max_radius: 6

Torus:
  center_placement_border: 4
  min_major_radius: 5
  max_major_radius: 5
  min_minor_radius: 2
  min_holes: 3
  max_holes: 3

Island:
  center_placement_border: 5
  min_outer_radius: 4
  max_outer_radius: 4
  min_inner_radius: 2
