python subsample_half.py ./subsampled_50/1_cube.npy ./subsampled_50/1_subsampled_cube.npy
python subsample_half.py ./subsampled_50/2_cube.npy ./subsampled_50/2_subsampled_cube.npy
python subsample_half.py ./subsampled_50/3_cube.npy ./subsampled_50/3_subsampled_cube.npy
python subsample_half.py ./subsampled_50/4_cube.npy ./subsampled_50/4_subsampled_cube.npy
python subsample_half.py ./subsampled_50/5_cube.npy ./subsampled_50/5_subsampled_cube.npy
python subsample_half.py ./subsampled_50/6_cube.npy ./subsampled_50/6_subsampled_cube.npy
python subsample_half.py ./subsampled_50/7_cube.npy ./subsampled_50/7_subsampled_cube.npy
python subsample_half.py ./subsampled_50/8_cube.npy ./subsampled_50/8_subsampled_cube.npy
python subsample_half.py ./subsampled_50/9_cube.npy ./subsampled_50/9_subsampled_cube.npy
python subsample_half.py ./subsampled_50/10_cube.npy ./subsampled_50/10_subsampled_cube.npy
python subsample_half.py ./subsampled_50/11_cube.npy ./subsampled_50/11_subsampled_cube.npy
python subsample_half.py ./subsampled_50/12_cube.npy ./subsampled_50/12_subsampled_cube.npy