Octopus:
  min_num_tentacles: 1
  max_num_tentacles: 2
  min_tentacle_length: 60
  max_tentacle_length: 70
  branching: False
  length_between_branches: 10
  shape: "Spheroid"
  min_width: 1
  max_width: 1

Tunnel:
  branching: False
  min_width: 1
  max_width: 2
  min_branching_length: 40
