Spheroid:
  center_placement_border: 4
  min_radius: 3
  max_radius: 5

Torus:
  center_placement_border: 4
  min_major_radius: 3
  max_major_radius: 3
  min_minor_radius: 1
  min_holes: 5
  max_holes: 5

Island:
  center_placement_border: 5
  min_outer_radius: 4
  max_outer_radius: 4
  min_inner_radius: 2
