Spheroid:
  center_placement_border: 4
  min_radius: 5
  max_radius: 7

Torus:
  center_placement_border: 4
  min_major_radius: 5
  max_major_radius: 5
  min_minor_radius: 2
  min_holes: 5
  max_holes: 5

Island:
  center_placement_border: 5
  min_outer_radius: 4
  max_outer_radius: 4
  min_inner_radius: 2
