Spheroid:
  center_placement_border: 5
  min_radius: 4
  max_radius: 7

Torus:
  center_placement_border: 5
  min_major_radius: 3
  max_major_radius: 5
  min_minor_radius: 1
  min_holes: 1
  max_holes: 3

Island:
  center_placement_border: 5
  min_outer_radius: 3
  max_outer_radius: 5
  min_inner_radius: 1
